services:
  - type: web
    name: teks-services
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd teks_project && gunicorn teks_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: teks-db
          property: connectionString

databases:
  - name: teks-db
    databaseName: teks_db
    user: teks_user
